"""
Django settings for contacts_crud project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load simple .env file (KEY=VALUE). This is a minimal, dependency-free loader
# so you can place SECRET_KEY=... in a .env file at the project root.
env_path = BASE_DIR / '.env'
if env_path.exists():
    try:
        with env_path.open() as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith('#'):
                    continue
                # allow 'export KEY=VALUE' style
                if line.startswith('export '):
                    line = line[len('export '):]
                if '=' not in line:
                    continue
                key, val = line.split('=', 1)
                key = key.strip()
                val = val.strip()
                # remove surrounding quotes
                if (val.startswith('"') and val.endswith('"')) or (
                    val.startswith("'") and val.endswith("'")
                ):
                    val = val[1:-1]
                # only set if not already in environment
                if key and key not in os.environ:
                    os.environ[key] = val
    except Exception:
        # don't hard-fail on .env parsing issues in development
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment (or .env loader above). When deploying
# to production make sure to set SECRET_KEY in the environment so the
# fallback dev key is not used.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-fallback-key')

# Read DEBUG from the environment. Use a simple truthy check so you can set
# DEBUG=0 or DEBUG=false in production env vars. Default to True for local dev.
DEBUG = str(os.environ.get('DEBUG', 'True')).lower() in ('1', 'true', 'yes')

# ALLOWED_HOSTS can be provided as a comma-separated env var, e.g.
# ALLOWED_HOSTS=example.com,www.example.com
raw_allowed = os.environ.get('ALLOWED_HOSTS', '')
if raw_allowed:
    cleaned = []
    for h in raw_allowed.split(','):
        h = h.strip()
        if not h:
            continue
        # If someone provided a full URL like https://example.com/ turn it
        # into the hostname portion so Django's ALLOWED_HOSTS matches.
        if '://' in h:
            try:
                parsed = urlparse(h)
                host = parsed.netloc
            except Exception:
                host = h
        else:
            host = h
        # strip any trailing slashes
        host = host.rstrip('/')
        if host:
            cleaned.append(host)
    # If VERCEL_URL is set (preview deployments), append its hostname so
    # preview hostnames are accepted even when ALLOWED_HOSTS was provided
    vercel_host = os.environ.get('VERCEL_URL')
    if vercel_host:
        try:
            if '://' in vercel_host:
                parsed = urlparse(vercel_host)
                vercel_host_clean = parsed.netloc
            else:
                vercel_host_clean = vercel_host
            vercel_host_clean = vercel_host_clean.rstrip('/')
        except Exception:
            vercel_host_clean = vercel_host
        if vercel_host_clean and vercel_host_clean not in cleaned:
            cleaned.append(vercel_host_clean)
    ALLOWED_HOSTS = cleaned
else:
    # If ALLOWED_HOSTS is not provided, try to include the Vercel runtime
    # host (VERCEL_URL). If that's not available, include a reasonable
    # default for this project and common local hosts so deployments work
    # without extra env vars during testing.
    vercel_host = os.environ.get('VERCEL_URL')
    # Normalize VERCEL_URL in case someone accidentally set it with a
    # scheme (https://...) or trailing slash. We need only the hostname
    # portion for Django's ALLOWED_HOSTS comparison.
    hosts = []
    if vercel_host:
        try:
            if '://' in vercel_host:
                parsed = urlparse(vercel_host)
                vercel_host_clean = parsed.netloc
            else:
                vercel_host_clean = vercel_host
            vercel_host_clean = vercel_host_clean.rstrip('/')
        except Exception:
            vercel_host_clean = vercel_host
        if vercel_host_clean:
            hosts.append(vercel_host_clean)
    else:
        # No VERCEL_URL available in the environment. For production
        # deployments prefer setting ALLOWED_HOSTS via the environment in
        # Vercel. Fall back to local development hosts so local runs
        # continue to work without editing this file.
        hosts.extend(['localhost', '127.0.0.1'])
    ALLOWED_HOSTS = hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact',
    'contact_method',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'contacts_crud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contacts_crud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    # fallback to local sqlite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Ensure these paths match your project structure
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles_build' / 'static'


# Use WhiteNoise to serve and compress files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# During development, serve files from the project-level `static/` folder.
# Add other paths here if you place static assets elsewhere.
STATICFILES_DIRS = [BASE_DIR / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
